// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVTXtgIlwBbWzlFfRxFvzb1y7wuuY4-Uo',
    appId: '1:168575364728:web:312725d48415cc4c71c78d',
    messagingSenderId: '168575364728',
    projectId: 'apps-fe0b7',
    authDomain: 'apps-fe0b7.firebaseapp.com',
    storageBucket: 'apps-fe0b7.firebasestorage.app',
    measurementId: 'G-CRXK9JYSLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_V0vqXMzvMpthx7-xRV1UDm_PbxO137s',
    appId: '1:168575364728:android:dfcea85ca85a6c5071c78d',
    messagingSenderId: '168575364728',
    projectId: 'apps-fe0b7',
    storageBucket: 'apps-fe0b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsRxMmzNKjUCniDOOEZ3ELVPf0Ey8cTmo',
    appId: '1:168575364728:ios:b44c07bcf4d5f3c971c78d',
    messagingSenderId: '168575364728',
    projectId: 'apps-fe0b7',
    storageBucket: 'apps-fe0b7.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsRxMmzNKjUCniDOOEZ3ELVPf0Ey8cTmo',
    appId: '1:168575364728:ios:b44c07bcf4d5f3c971c78d',
    messagingSenderId: '168575364728',
    projectId: 'apps-fe0b7',
    storageBucket: 'apps-fe0b7.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVTXtgIlwBbWzlFfRxFvzb1y7wuuY4-Uo',
    appId: '1:168575364728:web:6ac1a7012008300671c78d',
    messagingSenderId: '168575364728',
    projectId: 'apps-fe0b7',
    authDomain: 'apps-fe0b7.firebaseapp.com',
    storageBucket: 'apps-fe0b7.firebasestorage.app',
    measurementId: 'G-HR8MHLCSRS',
  );
}
